apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rp6aapvc3-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:a85086a550f472f3fae1c63ccecbc1ac58816c64@sha256:b6cc3b2f82957fd7293776615f9bc778bc7e051baf0ab58cd3cc82a5f7bec494
          name: container-image
